# Generated by Django 5.2.2 on 2025-09-24 21:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Acudiente',
            fields=[
                ('AcudienteId', models.AutoField(primary_key=True, serialize=False)),
                ('TipoId', models.CharField(max_length=50, verbose_name='Tipo ID')),
                ('NumId', models.CharField(max_length=50, unique=True)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Celular', models.CharField(max_length=20)),
                ('Parentesco', models.CharField(max_length=20)),
            ],
            options={
                'verbose_name': 'Acudiente',
                'verbose_name_plural': 'Acudientes',
                'db_table': 'Acudiente',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('IdUsuario', models.AutoField(primary_key=True, serialize=False)),
                ('TipoId', models.CharField(max_length=20)),
                ('NumId', models.CharField(max_length=10, unique=True)),
                ('Nombres', models.CharField(max_length=100)),
                ('Apellidos', models.CharField(max_length=100)),
                ('Rol', models.CharField(max_length=50)),
                ('Celular', models.CharField(blank=True, max_length=20, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Usuario',
                'verbose_name_plural': 'Usuarios',
                'db_table': 'Usuario',
            },
        ),
        migrations.CreateModel(
            name='Docente',
            fields=[
                ('IdDocente', models.AutoField(primary_key=True, serialize=False)),
                ('IdUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Docente',
                'verbose_name_plural': 'Docentes',
                'db_table': 'Docente',
            },
        ),
        migrations.CreateModel(
            name='Grado',
            fields=[
                ('IdGrado', models.AutoField(primary_key=True, serialize=False)),
                ('NumGrado', models.IntegerField(unique=True)),
                ('NumCurso', models.CharField(max_length=20)),
                ('NumEstudiantes', models.IntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Grado',
                'verbose_name_plural': 'Grados',
                'db_table': 'Grado',
                'unique_together': {('NumGrado', 'NumCurso')},
            },
        ),
        migrations.CreateModel(
            name='Estudiante',
            fields=[
                ('IdEstudiante', models.AutoField(primary_key=True, serialize=False)),
                ('IdUsuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('IdGrado', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.grado')),
            ],
            options={
                'verbose_name': 'Estudiante',
                'verbose_name_plural': 'Estudiantes',
                'db_table': 'Estudiante',
            },
        ),
        migrations.CreateModel(
            name='Materia',
            fields=[
                ('IdMateria', models.AutoField(primary_key=True, serialize=False, unique=True)),
                ('NombreMateria', models.CharField(max_length=50, unique=True)),
                ('IdDocente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.docente')),
            ],
            options={
                'verbose_name': 'Materia',
                'verbose_name_plural': 'Materias',
                'db_table': 'Materia',
            },
        ),
        migrations.CreateModel(
            name='Matricula',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('NumMatricula', models.CharField(max_length=100, unique=True, verbose_name='Número de Matrícula')),
                ('AnioLectivo', models.IntegerField(verbose_name='Año Lectivo')),
                ('NombreColegio', models.CharField(max_length=200, verbose_name='Nombre del Colegio de Procedencia')),
                ('FechaNacimientoEstudiante', models.DateField(verbose_name='Fecha de Nacimiento del Estudiante')),
                ('LugarNacimientoEstudiante', models.CharField(max_length=100, verbose_name='Lugar de Nacimiento del Estudiante')),
                ('BarrioVeredaEstudiante', models.CharField(max_length=100, verbose_name='Barrio/Vereda del Estudiante')),
                ('EPSSeguroMedicoEstudiante', models.CharField(max_length=100, verbose_name='EPS o Seguro Médico del Estudiante')),
                ('TieneCondicionMedica', models.BooleanField(default=False, verbose_name='¿Tiene alguna condición médica?')),
                ('EspecificacionCondicionMedica', models.TextField(blank=True, null=True, verbose_name='Especificar condición médica (si aplica)')),
                ('UltimoGradoCursado', models.CharField(max_length=50, verbose_name='Último Grado Cursado')),
                ('InstitucionAnterior', models.CharField(max_length=200, verbose_name='Institución Educativa Anterior')),
                ('CiudadMunicipioInstitucionAnterior', models.CharField(max_length=100, verbose_name='Ciudad/Municipio de la Institución Anterior')),
                ('RepiteGrado', models.BooleanField(default=False, verbose_name='¿Repite Grado?')),
                ('RequiereApoyoPedagogico', models.BooleanField(default=False, verbose_name='¿Requiere Apoyo Pedagógico?')),
                ('AutorizaTratamientoDatos', models.BooleanField(default=False, verbose_name='Autoriza Tratamiento de Datos')),
                ('DocIdentidadEstudiantePresentado', models.BooleanField(default=False, verbose_name='Documento de Identidad Estudiante Presentado')),
                ('CertificadoNotasAnteriorPresentado', models.BooleanField(default=False, verbose_name='Certificado de Notas Anterior Presentado')),
                ('FotocopiaCarnetVacunacionPresentado', models.BooleanField(default=False, verbose_name='Fotocopia Carnet de Vacunación Presentado')),
                ('FotocopiaEpsSeguroMedicoPresentado', models.BooleanField(default=False, verbose_name='Fotocopia EPS/Seguro Médico Presentado')),
                ('FotosTamanoDocumentoPresentadas', models.BooleanField(default=False, verbose_name='Fotos Tamaño Documento Presentadas')),
                ('CertificadoMedicoPresentado', models.BooleanField(default=False, verbose_name='Certificado Médico Presentado')),
                ('CopiaCedulaAcudientePresentado', models.BooleanField(default=False, verbose_name='Copia Cédula Acudiente Presentado')),
                ('ComprobanteResidenciaAcudientePresentado', models.BooleanField(default=False, verbose_name='Comprobante de Residencia Acudiente Presentado')),
                ('FechaMatricula', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Matrícula')),
                ('IdAcudiente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.acudiente')),
                ('IdEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.estudiante', verbose_name='Estudiante')),
                ('IdGrado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.grado', verbose_name='Grado a Matricular')),
            ],
            options={
                'verbose_name': 'Matrícula',
                'verbose_name_plural': 'Matrículas',
                'db_table': 'Matricula',
            },
        ),
    ]
