# Generated by Django 5.2.2 on 2025-09-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='acudiente',
            name='TipoId',
            field=models.CharField(max_length=50, verbose_name='Tipo Id'),
        ),
    ]
