# Generated by Django 4.2 on 2026-03-25 22:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0002_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Calificacion',
            fields=[
                ('IdCalificacion', models.AutoField(primary_key=True, serialize=False)),
                ('AnioLectivo', models.IntegerField(verbose_name='Año Lectivo')),
                ('Periodo', models.IntegerField(choices=[(1, 'Primer Periodo'), (2, 'Segundo Periodo'), (3, 'Tercer Periodo'), (4, 'Cuarto Periodo')], verbose_name='Periodo')),
                ('NombreActividad', models.CharField(max_length=100, verbose_name='Nombre de la Actividad')),
                ('Nota', models.DecimalField(decimal_places=2, max_digits=4, verbose_name='Nota')),
                ('Observaciones', models.TextField(blank=True, null=True, verbose_name='Observaciones')),
                ('FechaRegistro', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Registro')),
                ('FechaActualizacion', models.DateTimeField(auto_now=True, verbose_name='Fecha de Actualización')),
                ('IdDocente', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.docente', verbose_name='Docente')),
                ('IdEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.estudiante', verbose_name='Estudiante')),
                ('IdMateria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.materia', verbose_name='Materia')),
            ],
            options={
                'verbose_name': 'Calificación',
                'verbose_name_plural': 'Calificaciones',
                'db_table': 'Calificacion',
                'ordering': ['AnioLectivo', 'Periodo', 'IdEstudiante'],
                'unique_together': {('IdEstudiante', 'IdMateria', 'AnioLectivo', 'Periodo', 'NombreActividad')},
            },
        ),
    ]
