# Generated by Django 5.2.2 on 2025-09-29 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0002_alter_acudiente_tipoid'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='Activa',
            field=models.BooleanField(default=True, verbose_name='Matricula Activa'),
        ),
    ]
