# Generated by Django 4.2 on 2025-12-09 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0002_horario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('IdCertificado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(choices=[('estudio', 'Certificado de Estudio'), ('notas', 'Certificado de Notas'), ('conducta', 'Certificado de Conducta')], default='estudio', max_length=50)),
                ('nombre_institucion', models.CharField(default='INSTITUCIÓN EDUCATIVA AULATEC', max_length=200)),
                ('nit_institucion', models.CharField(default='900.123.456-7', max_length=20)),
                ('resolucion', models.CharField(default='Resolución No. 001234 del 15 de marzo de 2020 - Secretaría de Educación', max_length=500)),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente de Aprobación'), ('aprobado', 'Aprobado'), ('rechazado', 'Rechazado'), ('vencido', 'Vencido')], default='pendiente', max_length=20)),
                ('fecha_solicitud', models.DateTimeField(auto_now_add=True)),
                ('fecha_aprobacion', models.DateTimeField(blank=True, null=True)),
                ('fecha_vencimiento', models.DateTimeField(blank=True, null=True)),
                ('codigo', models.CharField(editable=False, max_length=50, unique=True)),
                ('archivo_pdf', models.CharField(blank=True, max_length=255, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('motivo_rechazo', models.TextField(blank=True, null=True)),
                ('nombre_completo_estudiante', models.CharField(blank=True, max_length=200)),
                ('documento_estudiante', models.CharField(blank=True, max_length=20)),
                ('grado_estudiante', models.CharField(blank=True, max_length=50)),
                ('IdEstudiante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='certificados', to='gestion_aulatec.estudiante')),
                ('aprobado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certificados_aprobados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Certificado',
                'verbose_name_plural': 'Certificados',
                'db_table': 'certificados',
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
