# Generated by Django 5.2.2 on 2025-10-02 01:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0003_matricula_activa'),
    ]

    operations = [
        migrations.AddField(
            model_name='matricula',
            name='AnioLectivo',
            field=models.CharField(max_length=20, default='2025'),
            preserve_default=False,
        ),
    ]
