# Generated by Django 5.2.8 on 2025-11-20 12:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0003_matricula_activa'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certificado',
            fields=[
                ('IdCertificado', models.AutoField(primary_key=True, serialize=False)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_emision', models.DateTimeField(auto_now_add=True)),
                ('codigo', models.CharField(max_length=50, unique=True)),
                ('archivo', models.CharField(blank=True, max_length=255, null=True)),
                ('estado', models.CharField(default='activo', max_length=20)),
                ('IdEstudiante', models.ForeignKey(db_column='IdEstudiante_id', on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.estudiante')),
                ('IdMateria', models.ForeignKey(blank=True, db_column='IdMateria_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.materia')),
                ('IdUsuario', models.ForeignKey(blank=True, db_column='IdUsuario_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'certificados',
            },
        ),
    ]
