# Generated by Django 5.2.2 on 2026-04-08 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0003_calificacion'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(default='temp@correo.com', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
