# Generated by Django 5.2.8 on 2025-11-22 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0004_certificado'),
    ]

    operations = [
        migrations.RunSQL(
            sql=(
                "ALTER TABLE certificado "
                "ADD COLUMN IF NOT EXISTS nit_institucion VARCHAR(20);"
            ),
            reverse_sql=(
                "ALTER TABLE certificado "
                "DROP COLUMN IF EXISTS nit_institucion;"
            ),
        ),
        migrations.AddField(
            model_name='certificado',
            name='nit_institucion',
            field=models.CharField(default='900.123.456-7', max_length=20),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='IdEstudiante',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.estudiante'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='IdMateria',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.materia'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='IdUsuario',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
