# Generated by Django 5.2.2 on 2025-11-27 20:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0004_fix_matricula'),
    ]

    operations = [
        migrations.AlterField(
            model_name='matricula',
            name='AnioLectivo',
            field=models.IntegerField(verbose_name='Año Lectivo'),
        ),
    ]
