# Generated by Django 5.2.2 on 2026-04-08 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0004_usuario_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='debe_cambiar_password',
            field=models.BooleanField(default=True),
        ),
    ]
