# Generated by Django 5.2.7 on 2025-10-27 02:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0005_alter_matricula_aniolectivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('IdRol', models.AutoField(primary_key=True, serialize=False)),
                ('NombreRol', models.CharField(max_length=50, unique=True)),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'Rol',
            },
        ),
        migrations.CreateModel(
            name='TipoIdentificacion',
            fields=[
                ('IdTipoId', models.AutoField(primary_key=True, serialize=False)),
                ('NombreTipo', models.CharField(max_length=100, verbose_name='Nombre del Documento')),
                ('Abreviatura', models.CharField(max_length=10, unique=True)),
            ],
            options={
                'verbose_name': 'Tipo de Identificación',
                'verbose_name_plural': 'Tipos de Identificación',
                'db_table': 'TipoIdentificacion',
            },
        ),
        migrations.RemoveField(
            model_name='acudiente',
            name='TipoId',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='BarrioVeredaEstudiante',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='CertificadoMedicoPresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='CertificadoNotasAnteriorPresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='CiudadMunicipioInstitucionAnterior',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='ComprobanteResidenciaAcudientePresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='CopiaCedulaAcudientePresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='DocIdentidadEstudiantePresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='EPSSeguroMedicoEstudiante',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='EspecificacionCondicionMedica',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='FechaNacimientoEstudiante',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='FotocopiaCarnetVacunacionPresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='FotocopiaEpsSeguroMedicoPresentado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='FotosTamanoDocumentoPresentadas',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='InstitucionAnterior',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='LugarNacimientoEstudiante',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='RepiteGrado',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='RequiereApoyoPedagogico',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='TieneCondicionMedica',
        ),
        migrations.RemoveField(
            model_name='matricula',
            name='UltimoGradoCursado',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='Rol',
        ),
        migrations.RemoveField(
            model_name='usuario',
            name='TipoId',
        ),
        migrations.AddField(
            model_name='estudiante',
            name='BarrioVereda',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Barrio/Vereda de Residencia'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='EPSSeguroMedico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='EPS o Seguro Médico'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='EspecificacionCondicionMedica',
            field=models.TextField(blank=True, null=True, verbose_name='Especificar condición médica'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='FechaNacimiento',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha de Nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='LugarNacimiento',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lugar de Nacimiento'),
        ),
        migrations.AddField(
            model_name='estudiante',
            name='TieneCondicionMedica',
            field=models.BooleanField(default=False, verbose_name='¿Tiene alguna condición médica?'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='Activa',
            field=models.BooleanField(default=True, verbose_name='Matrícula Activa'),
        ),
        migrations.AlterField(
            model_name='matricula',
            name='IdAcudiente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.acudiente', verbose_name='Acudiente'),
        ),
        migrations.CreateModel(
            name='ChecklistDocumentos',
            fields=[
                ('IdChecklist', models.AutoField(primary_key=True, serialize=False)),
                ('DocIdentidadEstudiantePresentado', models.BooleanField(default=False, verbose_name='Documento de Identidad Estudiante Presentado')),
                ('CertificadoNotasAnteriorPresentado', models.BooleanField(default=False, verbose_name='Certificado de Notas Anterior Presentado')),
                ('FotocopiaCarnetVacunacionPresentado', models.BooleanField(default=False, verbose_name='Fotocopia Carnet de Vacunación Presentado')),
                ('FotocopiaEpsSeguroMedicoPresentado', models.BooleanField(default=False, verbose_name='Fotocopia EPS/Seguro Médico Presentado')),
                ('FotosTamanoDocumentoPresentadas', models.BooleanField(default=False, verbose_name='Fotos Tamaño Documento Presentadas')),
                ('CertificadoMedicoPresentado', models.BooleanField(default=False, verbose_name='Certificado Médico Presentado')),
                ('CopiaCedulaAcudientePresentado', models.BooleanField(default=False, verbose_name='Copia Cédula Acudiente Presentado')),
                ('ComprobanteResidenciaAcudientePresentado', models.BooleanField(default=False, verbose_name='Comprobante de Residencia Acudiente Presentado')),
                ('IdMatricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.matricula', verbose_name='Matrícula Asociada')),
            ],
            options={
                'verbose_name': 'Checklist Documentos',
                'verbose_name_plural': 'Checklist Documentos',
                'db_table': 'ChecklistDocumentos',
            },
        ),
        migrations.CreateModel(
            name='HistorialAcademico',
            fields=[
                ('IdHistorial', models.AutoField(primary_key=True, serialize=False)),
                ('UltimoGradoCursado', models.CharField(max_length=50, verbose_name='Último Grado Cursado')),
                ('InstitucionAnterior', models.CharField(max_length=200, verbose_name='Institución Educativa Anterior')),
                ('CiudadMunicipioInstitucionAnterior', models.CharField(max_length=100, verbose_name='Ciudad/Municipio de la Institución Anterior')),
                ('RepiteGrado', models.BooleanField(default=False, verbose_name='¿Repite Grado?')),
                ('RequiereApoyoPedagogico', models.BooleanField(default=False, verbose_name='¿Requiere Apoyo Pedagógico?')),
                ('IdMatricula', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='gestion_aulatec.matricula', verbose_name='Matrícula Asociada')),
            ],
            options={
                'verbose_name': 'Historial Académico',
                'verbose_name_plural': 'Historiales Académicos',
                'db_table': 'HistorialAcademico',
            },
        ),
        migrations.AddField(
            model_name='usuario',
            name='IdRol',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.rol'),
        ),
        migrations.AddField(
            model_name='acudiente',
            name='IdTipoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.tipoidentificacion', verbose_name='Tipo Id'),
        ),
        migrations.AddField(
            model_name='usuario',
            name='IdTipoId',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='gestion_aulatec.tipoidentificacion'),
        ),
    ]
