# Generated by Django 4.2 on 2026-04-11 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0006_certificado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='Email',
            field=models.EmailField(blank=True, default=None, max_length=255, null=True, unique=True),
        ),
    ]
