# Generated by Django 4.2 on 2026-04-22 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0007_alter_usuario_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grado',
            name='NumGrado',
            field=models.IntegerField(),
        ),
    ]
