# Generated by Django 4.2 on 2026-04-23 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion_aulatec', '0008_alter_grado_numgrado'),
    ]

    operations = [
        migrations.AddField(
            model_name='estudiante',
            name='ultima_descarga_notas',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última descarga de reporte de notas'),
        ),
        migrations.AlterField(
            model_name='certificado',
            name='tipo',
            field=models.CharField(choices=[('estudio', 'Certificado de Estudio'), ('notas', 'Certificado de Notas')], default='estudio', max_length=50),
        ),
    ]
